"""budget_type_no_category

Revision ID: e639e1625733
Revises: 2afab6a5a827
Create Date: 2026-06-08 22:38:35.799898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e639e1625733'
down_revision: Union[str, None] = '2afab6a5a827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    budgettype = sa.Enum('monthly', 'yearly', name='budgettype')
    budgettype.create(op.get_bind(), checkfirst=True)
    op.add_column('budgets', sa.Column('budget_type', sa.Enum('monthly', 'yearly', name='budgettype'), nullable=True))
    op.execute("UPDATE budgets SET budget_type = 'monthly'")
    op.alter_column('budgets', 'budget_type', nullable=False)
    op.alter_column('budgets', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('budgets_category_id_fkey', 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('budgets_category_id_fkey', 'budgets', 'categories', ['category_id'], ['id'])
    op.alter_column('budgets', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('budgets', 'budget_type')
    # ### end Alembic commands ###
